[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window]
padding={x=1, y=1}
opacity = 0.6

[font]
size=7
normal = { family = "JetBrainsMonoNLNerdFont" }
bold = { family = "JetBrainsMonoNLNerdFont" }
italic = { family = "JetBrainsMonoNLNerdFont" }
bold_italic = { family = "JetBrainsMonoNLNerdFont" }

[colors.primary]
background = '0x000000'
foreground = '0xD4D4D4'
#
# [colors.normal]
# black = '0x1E1E1E'
# red = '0xF44747'
# green = '0x608B4E'
# yellow = '0xD7BA7D'
# blue = '0x569CD6'
# magenta = '0xC586C0'
# cyan = '0x9CDCFE'
# white = '0xD4D4D4'

[env]
TERM = "xterm-256color"

