#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1:web 2:zellij 3:code 4:api 5:db 6:nil 7:nil 8:nil 9:music 0:misc

bspc config border_width 1
bspc config window_gap 7

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sxhkd &
picom --config /home/rk/.config/picom/picom.conf &
feh --bg-scale /home/rk/Pictures/bg.jpg
polybar &
