[general]

[window]
opacity = 0.8

[font]
size=8
normal = { family = "Iosevka Term" }
bold = { family = "Iosevka Term" }
italic = { family = "Iosevka Term" }
bold_italic = { family = "Iosevka Term" }

[colors.primary]
background = '0x000000'
foreground = '0xD4D4D4'
#
# [colors.normal]
# black = '0x1E1E1E'
# red = '0xF44747'
# green = '0x608B4E'
# yellow = '0xD7BA7D'
# blue = '0x569CD6'
# magenta = '0xC586C0'
# cyan = '0x9CDCFE'
# white = '0xD4D4D4'

[env]
TERM = "xterm-256color"

